### ISSUE TITLE
Installation issues with mac

### ISSUE THREAD

**Issue by samanway-sprinklr** [bugbash/selenium-kiwix#11]
When the software for mac version is downloaded, the zim files do not come as bundled with it unlike for windows ,and after the installation is successfully, the user might be clueless about how to view the contents.

**Comment by kelson42** [comment]
Thank you for your pertinent feedback. I perfectly agree with this. 

That's why new version of Kiwix ask for downloading the online catalog and invite the user to display it as soon as it is downloaded. You might download this version here:
http://download.kiwix.org/bin/0.9/

That way, users can not be "clueless" any more :)
