### ISSUE TITLE
Empty links are present

### ISSUE THREAD

**Issue by saksham-srivastava** [bugbash/selenium-kiwix#23]
Links that do not open up offline and online are also present. They should either be implemented or should not be given there in first place.

**Comment by kelson42** [comment]
Could you give us a concrete example?

**Comment by kelson42** [comment]
Thank you for your bug report. External links should be displayed with a small icon indicating that this link is an external link. This is the only way to make quickly the difference between internal and external links. Unfortunately this was not done with the "Ray Charles" ZIM files (and all files made with the extension:collection running on Wikipedia.org). I have open a bug regarding this bug here:
https://bugzilla.wikimedia.org/show_bug.cgi?id=30199 and it's the official place where this is tracked.
