### ISSUE TITLE
Search containing partial words does not work

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#31]
Steps to reproduce:
1. Open the zim file - wikipedia_en_ray_charles_03_2013.zim in Kiwix 0.9
2. Confirm generation of Index
3. In the Search box, Start typing 'Sou' 

The  following options starting with 'Soul' get displayed
Soul Brothers
Soul Meeting
Soul Brothers
Soul Meeting
Containing Sou
1. Select the option 'Containing Sou'

Actual output:
No result were found for Sou 

Expected:
Search should Titles that contain the text 'Sou' which includes Soul , Sour etc.

**Comment by soloturn** [comment]
the index is already big, so i am not sure if this is a good idea. did wildcards (*) as well not work? see here for some additional information:
http://stackoverflow.com/questions/5786338/document-search-on-partial-words

**Comment by vinithrasp** [comment]
I have tried Wildcards (*) and they do not seem to work either.

**Comment by kelson42** [comment]
The last suggestion "containing Sou' refers to the Kiwix fulltext search feature. This fulltext search is different from the suggestions system and needs the creation of a fulltext index.

You bug report is right, a result should be display with all the articles containing the word "sous". You probably don't have a result because there was no fulltext index created for this content. You might create one with the menu entry "tools > create index".

So, what I have done, is that I have removed this suggestion entry "containing..." if no fulltext search engine is created/available. You can check this with one of the last nightly builds:
http://download.kiwix.org/bin/nightly/

Thank you very much for your pertinent bug report.
