### ISSUE TITLE
Nexus7 - Contact - Upon clicking an e-mail address available in the application, web e-mail option is not made available.

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#63]
This behaviour is observed when clicked on the e-mail address - info@soschildren.org

**Comment by kelson42** [comment]
I have tried to reproduce the problem. In my case it pop ups a dialog box with two choices ("email" for the email app et "Gmail" for... gmail).

So, to my opinion, this is a perfect handling. This shows that Kiwix relies on the Android OS to deal with the email address (mailto protocol).

@aarjay If not all optinos are shown in your case this can be due to (1) a misconfiguration of your device (2) an error in your android version.

**Comment by aarjay** [comment]
Thanks for the reply kelson, I do not have the device but if I get hold of one, I will investigate further for the appropriate reason for failure.
