### ISSUE TITLE
Idea: If new content or an update is available for a page, the users can be notified/communicated. 

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#7]
Suggestion: While downloading ask for and provide an email address. 
The users are notified of the update via an email.  
Email options : Individual , Organizational

**Comment by rashiq** [comment]
I personally, don't like the asking-for-email approach, since it could be possible to just check for updates within the app itself. 
I'm not sure if the desktop versions already have that, but I'm planning to add an updater to the Android version as discussed at #12.

@kelson42 do the desktop versions offer updating the zim files if a new one is available? 

Additionally, asking for an email address may raise privacy concerns.
Thanks for the suggestion though!

**Comment by kelson42** [comment]
I also think that email is not the best way. For now Kiwix informs if new content are available, but it's not really the same that telling that you have a new version of your content.

I think Kiwix should tell you if you have a new version online of a content you have installed offline (like you say in your email). But to do that we need to introduce a way to identifiy different version of a same content with a unique ID in the ZIM file.

That's where we are currently, I'll post later the correct pointers (other bug tickets related).

**Comment by aarjay** [comment]
Having updates emailed for every page/content is not a feasible option. Thanks Rashiq and Kelson.

**Comment by kelson42** [comment]
On desktop version of Kiwix, users are triggered if new content are published.

Being able to automatically update the content (or trigger the user) if an update is available for a specific content is an old request which is tracked upstream here:
https://sourceforge.net/p/kiwix/feature-requests/695/

This is a feature request for Android too, which of course depends of the implementation of an internal content/download manager:
https://sourceforge.net/p/kiwix/feature-requests/784/

Subscribe these tickets if you want to be kept informed about the progress.
