### ISSUE TITLE
[Team S-cube][Severe]Kiwix crashes while trying to open the file

### ISSUE THREAD

**Issue by devishree90** [bugbash/selenium-kiwix#71]
Precondition

There is file which is already downloaded.( i.e Wikipedia_en_ray_charles_03_2013).User is seeing the content of the downloaded file

Steps to Reproduce

Select Options->Open File
Select the file which is already open(In this case,Wikipedia_en_ray_charles_03_2013) from the list of files

Actual
Kiwix hangs and returns the message " Unfortuntely,Kiwix has stopped"

Environment
Android:4.4.4

**Comment by kelson42** [comment]
I can not reproduce the error. I guess your file is corrupted, could you please upload here a copy of the ZIM file you are using?

**Comment by kelson42** [comment]
We have fixed last night a 4.4 specific crash scenario. Could you please test with this nightly build:
http://download.kiwix.org/bin/nightly/2014-10-18/kiwix-20141018_491072d3-android.apk

Otherwise, just report the crash with the Android crash reporter and let us know what comment have you put (so we can identify it)?
