### ISSUE TITLE
Intermittent zim load error when traversing through Bookmarks from different zim files

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#73]
Environment:
OS: Win 7 64-bit

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim files - wikipedia_as_all_07_2013.zim and wikipedia_en_ray_charles_03_2013.zim
3. Launch Kiwix and open the above files downloaded in Step 2
4. Bookmark couple of pages in the above zim files and try to traverse pages from the 2 zim files alternatively.

Actual Behavior:
 After the confirmation asking that the content is from another file, application intermittently fails to load the zim file and throws error.

PFA the screenshot of the error thrown on valid zim file.

**Comment by vinithrasp** [comment]
![missing_zim_file](https://cloud.githubusercontent.com/assets/8127422/4200670/69459a48-3814-11e4-95e7-37dfe38119d1.png)

**Comment by kelson42** [comment]
The problem was that the bookmarks were not saving the file where they were from (only the article title). In other words, that means that the bookmarking system was always assuming you have currently open the right ZIM file.

This is fixed in the 0.9 final (But you still need to renew your "old" bookmarks to get this working correctly):
http://download.kiwix.org/bin/0.9/

Thank you anyway for your report.
