### ISSUE TITLE
[Usability] Same Hot (Access) key 'S' for both Skin and Status Bar in Display Menu

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#80]
Skin and Status Bar both have been provided with the same access key 'S' which should be unique.

PFA the screenshot highlighting the issue.

**Comment by vinithrasp** [comment]
![same_access_key](https://cloud.githubusercontent.com/assets/8127422/4198036/9728988c-37f3-11e4-92fc-8604ab6880ce.png)

**Comment by kelson42** [comment]
Thank you for your bug report.

This ticket seems to be pretty easy to fix but is not at all. The problem is to achieve to allow smart access keys for all menus to each language (more than 100 languages). This is really a huge task.

That's why we should find an automatic solution to help us. Here is the upstream ticket:
https://sourceforge.net/p/kiwix/feature-requests/476/
