### ISSUE TITLE
[Documentation] Include documentation/help on Browse Library->Get new files

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#82]
Browse Library -> Get new files shows up as empty page on initial launch of Kiwix app and the user has no clue on the feature/functionality.

Please include some Tool Tip/Help on this menu item.

**Comment by kelson42** [comment]
Thank you for your feedback. This is fixed in the 0.9 final:
http://download.kiwix.org/bin/0.9/

The user get asked if he wants to download the catalog, and at the end get routed to the list of content available to download. If he is not online he stays on the help page (which still needs to be translated to all languages, but this is another issue https://sourceforge.net/p/kiwix/bugs/743/.
