### ISSUE TITLE
Dialog boxes in Vernacular (Tamil) has OK and Cancel buttons in English

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#85]
Environment:
OS: Win 7 64-bit

Version: Kiwix 0.9

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Launch Kiwix and change Language to Tamil
3. Try to change skin 

Actual behavior:
Confirmation Pop up comes up with Ok and Cancel button in English

Desired behavior:
Ok and Cancel should come up in Vernacular (Tami;l) as chosen by the user

PFA the screenshot with issue highlighted

**Comment by kelson42** [comment]
This should be fixed in the last dev. version. Download and test it:
http://download.kiwix.org/bin/0.9/

But, the translation in Tamil of the Kiwix UI is not finished. Your help would be really welcome at:
https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&language=ta&filter=!translated&action=translate

**Comment by vinithrasp** [comment]
![ok_cancel_tamil](https://cloud.githubusercontent.com/assets/8127422/4200631/e9c07d6a-3813-11e4-8ee8-ff2af09e617a.png)

**Comment by kelson42** [comment]
Thank you very much for the screenshot.

It's now fixed, see the patch:
https://github.com/kiwix/kiwix_mirror/commit/894b44172abae361c12755f1fa59dc0dbcff63db

Here a compiled version for Windows (
![screenshot from 2014-09-12 18 58 26](https://cloud.githubusercontent.com/assets/1029718/4253702/6cca846c-3aa3-11e4-9fec-a350b563302a.png)
including the patch):
http://download.kiwix.org/nightly/bin/2014-09-12/kiwix-20140912_49e1e59a-win.zip

Regards
Emmanuel
