### ISSUE TITLE
[Android] Kiwix app have major issues when Telugu language is selected.

### ISSUE THREAD

**Issue by ashokgadamsetty** [bugbash/selenium-kiwix#88]
1. Select language Telugu.

Issue:
- Only few items in settings menu converted to telugu. That too, some items in settings still shows in english.
- Search text still shows in english.
- Click on Help, every thing shows in english.
- Kiwix app name, tag line, page title, content still shows in english.
- ‘Share with Friends’ still shows in english.

When language changed, you change 6 items in the settings to telugu and nothing else and say you support, Telugu language? This is very very bad user experience...I mean it.

**Comment by testertested** [comment]
If I were you, I would say "what happens when selected Telugu" language than to say it sucks. Why because the human on the other side you expect to take action would focus on your emotion than on the technical problem you are reporting. 

The beauty of what you did is to give yourselves a learning opportunity. That is nice.

**Comment by soloturn** [comment]
is this true? translatewiki says, everything is translated:
https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&filter=translated&action=translate&language=te

**Comment by ashokgadamsetty** [comment]
I understand, sorry for that..I raised  other bugs where it app itself
crashed..but for this bug, I was very frustrated..
But this is how customers react..
If I were you, I would not say we support 140 languages or so.

Sent from my iPhone

On 06-Sep-2014, at 10:21 am, Pradeep Soundararajan notifications@github.com
wrote:

If I were you, I would say "what happens when selected Telugu" language
than to say it sucks. Why because the human on the other side you expect to
take action would focus on your emotion than on the technical problem you
are reporting.

The beauty of what you did is to give yourselves a learning opportunity.
That is nice.

**Comment by ashokgadamsetty** [comment]
I tested on android tablet I was given, issue was there.
I already showed to the people from your company.

If any tool says, every thing is translated, that's blunder I feel.
Please read through all issues I mentioned in this bug.

Sent from my iPhone

On 06-Sep-2014, at 3:26 pm, rthurner notifications@github.com wrote:

is this true? translatewiki says, everything is translated:
https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&filter=translated&action=translate&language=te

**Comment by soloturn** [comment]
would you be able to translate the help text into telugu please?

**Comment by kelson42** [comment]
Hi  @ashokgadamsetty 

Our main app which is the desktop app is mainly translated to Telegu. That's why this is written on the Web site that Kiwix is localised in Telegu. The Android app is a really new port which unfortunately is not so mature like the desktop one. I feel sorry for your disappointment but the Android UI is now almost fully translated in Telegu (only one string left https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&language=te&filter=!translated&action=translate), so next version should be a lot better for Telegu native speakers.

Anyway all that stuff is _only about the software UI_, never about the content. You can perfectly load a content in English with a software in Telegu.

The last point you have raised up was the welcome/help page which should still be translated in local languages like Telegu. I agree and that's why I have created the upstream ticket here to track the issue:
https://sourceforge.net/p/kiwix/bugs/743/

Thank you very much for you report, although it hat a little bit the taste of frustration.

Regards
Emmanuel
