### ISSUE TITLE
Nexus7 - Zoom controls are available when the settings for zoom control is disabled.

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#9]
Device - Nexus7 
zim - Wikipedia for schools 
Application settings - Zoom controls are available when the settings for zoom control is disabled.

**Comment by rashiq** [comment]
Is this by chance the case when the zoom controls are activated and the, again, disabled? 
Because I have been noticing that well. That is unfortunately due to us using a hack to disable the zoom controls, since the default `WebView` doesn't support turning the controls off and on again. 

But I'll look into it again, maybe I missed something.

**Comment by aarjay** [comment]
True Rashiq. 
This behaviour is observed when zoom control is enabled and then disabled.

**Comment by kelson42** [comment]
I confirm the bug too. This is now reported upstream (and will be tracked here):
https://sourceforge.net/p/kiwix/bugs/752/

@aarhay Thank you very much for reporting that bug.

**Comment by kelson42** [comment]
Fixed in next Kiwix release.
